name: HPC CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: quay.io/singularity/singularity:v3.5.3

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        env:
          CLIENT: ${{ secrets.CLIENT }}
        run: /bin/bash .github/workflows/setup.sh
      - name: Create token file
        env:
          SYLABS_TOKEN: ${{ secrets.SYLABS_TOKEN }}
        run: echo "$SYLABS_TOKEN" > token_file
      - name: Login Sylabs
        run: singularity remote login --tokenfile token_file
      - name: Build Singularity image
        run: singularity build --remote Singularity.simg Singularity
      - name: Send files
        env:
          CREDENTIALS_GOOGLE: ${{ secrets.CREDENTIALS_GOOGLE }}
          COLLECTION_CONTAINER: ${{ secrets.COLLECTION_CONTAINER }}
          ACCESS_KEY_AWS: ${{ secrets.ACCESS_KEY_AWS }}
          SECRET_KEY_AWS: ${{ secrets.SECRET_KEY_AWS }}
          TESTE: ${{ secrets.TESTE }}
        run: /bin/bash .github/workflows/send.sh google Singularity Singularity.simg
