name: HPC CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: quay.io/singularity/singularity:v3.5.3

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: /bin/bash .github/workflows/setup.sh
      - name: Build Singularity image
        run: echo $SYLABS_TOKEN > token_file && singularity remote login --tokenfile token_file && singularity build --remote Singularity.simg Singularity
      - name: Send files
        run: /bin/bash .github/workflows/send.sh google Singularity Singularity.simg
