name: HPC CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: quay.io/singularity/singularity:v3.5.3

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: /bin/bash .github/workflows/setup.sh
      - name: Build image and send files
        env:
          RECIPE: ${{ secrets.RECIPE }}
          ID_GOOGLE: ${{ secrets.ID_GOOGLE }}
          SECRET_GOOGLE: ${{ secrets.SECRET_GOOGLE }}
          TOKEN_GOOGLE: ${{ secrets.TOKEN_GOOGLE }}
          COLLECTION_CONTAINER: ${{ secrets.COLLECTION_CONTAINER }}
          ACCESS_KEY_AWS: ${{ secrets.ACCESS_KEY_AWS }}
          SECRET_KEY_AWS: ${{ secrets.SECRET_KEY_AWS }}
          CLIENT: ${{ secrets.CLIENT }}
        run: echo "Singularit Recipe - ${RECIPE}" && /bin/bash .github/workflows/send.sh
